FROM node:22-slim

WORKDIR /app

# Kopiuj package files
COPY package*.json ./
RUN npm ci

# Kopiuj resztę projektu
COPY . .

# Zbuduj Next.js
RUN npm run build

# Port
EXPOSE 3000

# Start produkcyjny
CMD ["npm", "run", "start"]